### ISSUE TITLE
Composer signature missmatch

### ISSUE THREAD

**Issue by josealgardataborges** [andynoelker/laravel-5-view-generator#1]
While doing a simple:

composer global require andynoelker/laravel-5-view-generator

I got the following answer:

[Composer\Repository\RepositorySecurityException] The contents of http://packagist.org/p/andynoelker/laravel-5-view-generator%24bf72c99a4c5a68c47a9868e717a2f9456aa5bf024d79cd0cf538fb6acb2ea7e3.json do not match its signature. This should indicate a man-in-the-middle attack. Try running composer again and report this if you think it is a mistake.

**Comment by andynoelker** [comment]
Take a peek at [#1431](https://github.com/composer/composer/issues/1431) on composer's repo. People have been having this issue from time for the past few years. Packagist updates a package's signature every minute for security reasons and it seems like this problem occurs when your network is having some trouble downloading the package before the update occurs again. Are you using a VPN or proxy? It looks like that is the most common cause of this error. I just wiped my machine and did a `composer global require` of the package and it worked perfectly fine, so I don't believe this is anything specific to this package. I'd suggest wiping your composer cache (`composer clear-cache`), trying a few more times to download it, and try on a different connection if at all possible.

**Comment by josealgardataborges** [comment]
@andynoelker did not need to clear the composer cache, it just worked this time. Thanks for the info and sorry for the false alarm.

U:>composer global require andynoelker/laravel-5-view-generator
Changed current directory to C:/Users/jose.borges/AppData/Roaming/Composer
Using version ^1.0 for andynoelker/laravel-5-view-generator
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
- Installing doctrine/inflector (v1.1.0)
  Loading from cache
- Installing illuminate/contracts (v5.2.7)
  Loading from cache
- Installing illuminate/support (v5.2.7)
  Loading from cache
- Installing andynoelker/laravel-5-view-generator (1.0)
  Downloading: 100%
